import { test, expect } from '@playwright/test'

test('recorrido manual: examen mañana, rapid, 60 minutos y plan no intrusivo', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 768 })
  await page.goto('/materias?adaptive-product-real=1&days=1&mode=quick_test&exam=unknown&minutes=60&micros=9')
  const plan = page.getByTestId('real-plan-controls')
  await expect(plan).toBeVisible()
  await expect(plan).toHaveAttribute('data-panel-open', 'false')
  expect(Number(await plan.getAttribute('data-plan-session-count'))).toBeGreaterThan(1)
  await expect(page.getByTestId('real-readiness')).toContainText('Cobertura 0%')
  await expect(page.locator('body')).not.toContainText(/Trabajar los conceptos asignados|Concepto no relacionado|Información externa/)
  await page.getByTestId('open-plan-drawer').click()
  await expect(page.getByText(/Puedes estudiar más|también puedes continuar/i)).toBeVisible()
  const future = new Date(Date.now() + 30 * 60 * 60_000)
  await page.getByTestId('exam-date-input').fill(future.toISOString().slice(0, 16))
  await page.getByTestId('save-exam-date').click()
  await expect(plan).toHaveAttribute('data-exam-at', /T/)
  await page.getByTestId('close-plan-drawer').click()
  await expect(page.getByTestId('plan-drawer')).toHaveCount(0)
})
