import { test, expect, type Page } from '@playwright/test'

const open = async (page: Page, query = '') => {
  await page.goto(`/materias?adaptive-product-real=1${query}`)
  await expect(page.getByTestId('real-plan-controls')).toBeVisible()
  return page.getByTestId('real-plan-controls')
}
const openDrawer = async (page: Page) => { await page.getByTestId('open-plan-drawer').click(); await expect(page.getByTestId('plan-drawer')).toBeVisible() }

test('01 examen mañana y rapid atraviesan /materias', async ({ page }) => { const plan = await open(page, '&days=1&mode=quick_test'); await expect(plan).toHaveAttribute('data-exam-at', /T/) })
test('02 semana y writing muestran plan real', async ({ page }) => { const plan = await open(page, '&days=7&mode=write_explain'); await expect(plan).toHaveAttribute('data-plan-session-count', /[4-9]/) })
test('03 mes y mixed muestran plan real', async ({ page }) => { const plan = await open(page, '&days=30&mode=mix_everything'); expect(Number(await plan.getAttribute('data-plan-session-count'))).toBeGreaterThan(4) })
test('04 tiempo insuficiente se muestra en producto', async ({ page }) => { await open(page, '&days=1&micros=80&minutes=20'); await openDrawer(page); await expect(page.getByTestId('plan-feasibility')).toContainText(/estimado/i) })
test('05 reorganización es opcional y revisa el plan real', async ({ page }) => { await open(page); await openDrawer(page); await page.getByTestId('miss-current-session').click(); await expect(page.getByTestId('plan-change-message')).toBeVisible() })
test('06 reprogramar es una acción real dentro del drawer', async ({ page }) => { await open(page); await openDrawer(page); await page.getByTestId('reschedule-current-session').click(); await expect(page.getByTestId('plan-change-message')).toBeVisible() })
test('07 cambiar fecha redistribuye', async ({ page }) => { const plan = await open(page); await openDrawer(page); const before = await plan.getAttribute('data-exam-at'); const date = new Date(Date.now() + 12 * 86_400_000); await page.getByTestId('exam-date-input').fill(date.toISOString().slice(0,16)); await page.getByTestId('save-exam-date').click(); await expect(plan).not.toHaveAttribute('data-exam-at', before!) })
test('08 cambio de fecha persiste tras refresh', async ({ page }) => { const plan = await open(page); await openDrawer(page); const date = new Date(Date.now() + 11 * 86_400_000); await page.getByTestId('exam-date-input').fill(date.toISOString().slice(0,16)); await page.getByTestId('save-exam-date').click(); const changed = await plan.getAttribute('data-exam-at'); await page.reload(); await expect(page.getByTestId('real-plan-controls')).toHaveAttribute('data-exam-at', changed!) })
test('09 readiness real separa tres métricas', async ({ page }) => { await open(page); await expect(page.getByTestId('real-readiness')).toContainText('Cobertura'); await expect(page.getByTestId('real-readiness')).toContainText('Dominio'); await expect(page.getByTestId('real-readiness')).toContainText('Preparación') })
test('10 required micros no se pierden al revisar', async ({ page }) => { const plan = await open(page); await openDrawer(page); const before = new Set((await plan.getAttribute('data-required-ids'))!.split(',')); await page.getByTestId('miss-current-session').click(); expect(new Set((await plan.getAttribute('data-required-ids'))!.split(','))).toEqual(before) })
test('11 StudyPlan y ejecutables están sincronizados', async ({ page }) => { const plan = await open(page); expect(await plan.getAttribute('data-plan-session-count')).toBe(await plan.getAttribute('data-executable-session-count')) })
test('12 sincronización sobrevive revisión', async ({ page }) => { const plan = await open(page); await openDrawer(page); await page.getByTestId('miss-current-session').click(); expect(await plan.getAttribute('data-plan-session-count')).toBe(await plan.getAttribute('data-executable-session-count')) })
test('21 panel compacto no tapa el libro y drawer conserva foco', async ({ page }) => { const plan = await open(page); await page.setViewportSize({ width: 1440, height: 768 }); await expect(plan).toHaveAttribute('data-panel-open', 'false'); await expect(page.getByTestId('plan-drawer')).toHaveCount(0); await openDrawer(page); await expect(page.getByTestId('close-plan-drawer')).toBeFocused(); await page.getByTestId('close-plan-drawer').click(); await expect(page.getByTestId('plan-drawer')).toHaveCount(0) })
test('13 todas las asignaciones pertenecen al required set', async ({ page }) => { const plan = await open(page); const required = new Set((await plan.getAttribute('data-required-ids'))!.split(',')); for (const id of (await plan.getAttribute('data-assigned-ids'))!.split(',').filter(Boolean)) expect(required.has(id)).toBeTruthy() })
test('14 ninguna sesión se crea después del examen', async ({ page }) => { const plan = await open(page, '&days=1'); const exam = new Date((await plan.getAttribute('data-exam-at'))!).getTime(); expect(exam).toBeGreaterThan(Date.now()) })
test('15 formato matemático llega al plan real', async ({ page }) => { const plan = await open(page, '&exam=mathematical'); await expect(plan).toHaveAttribute('data-exam-format', 'mathematical') })
test('16 development llega al final exam', async ({ page }) => { const plan = await open(page, '&exam=development'); await expect(plan).toHaveAttribute('data-exam-format', 'development') })
test('17 coverage cero no fabrica dominio', async ({ page }) => { await open(page); await expect(page.getByTestId('real-readiness')).toContainText('Cobertura 0%'); await expect(page.getByTestId('real-readiness')).toContainText('Dominio 0%') })
test('18 program complete no aparece sin mastery', async ({ page }) => { await open(page); await expect(page.getByText(/programa completado/i)).toHaveCount(0) })
test('19 controles reales no exponen microIds al estudiante', async ({ page }) => { await open(page); await expect(page.locator('body')).not.toContainText('fixture_micro_') })
test('20 pausa restaura diálogo, actividad y fase tras refresh', async ({ page }) => {
  await page.route('**/api/adaptive/v3/build-graph', route => route.fulfill({ json: { success: true, graph: { totalMicros: 9 }, stats: { bankMs: 0 } } }))
  await page.route('**/api/adaptive/v3/tutor', async route => { const body = route.request().postDataJSON(); await route.fulfill({ json: { success: true, requestId: body.requestId, sessionId: 'plan_learn_1', page: { type: 'theory', title: 'Fundamentos', content: { blocks: [{ type: 'text', text: 'Contenido de enseñanza real' }] } }, systemInfo: { progress: 1 }, coverageReport: { studiedMicroIds: [], provisionallyMasteredMicroIds: [], reinforcementMicroIds: [] } } }) })
  await open(page)
  await page.getByRole('button', { name: /ABRIR EL LIBRO/ }).click()
  await expect(page.getByRole('button', { name: /Página siguiente/ })).toBeVisible()
  await page.getByRole('button', { name: /EMPEZAR ESTA SESIÓN/ }).last().click()
  await expect(page.getByTestId('pause-session')).toBeVisible()
  await page.getByTestId('pause-session').click()
  await expect(page.getByTestId('session-paused')).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('studyal_v3_paused_session'))).toContain('"paused":true')
  await page.reload()
  expect(await page.evaluate(() => localStorage.getItem('studyal_v3_paused_session'))).toContain('"paused":true')
  await expect(page.getByTestId('session-paused')).toBeVisible()
  await page.getByTestId('resume-session').click()
  await expect(page.getByTestId('session-paused')).toHaveCount(0)
})
