"use client"

import { useMemo, useState, type CSSProperties } from "react"
import type { GeometryCanvasDataSpec, SourceImageDataSpec, StructureGraphDataSpec, FlowStateDataSpec, EquationExpressionDataSpec, VisualInteractionMode, VisualInteractionVerb } from "../../lib/adaptive/visual/visualContract"

const card:CSSProperties={border:"1px solid #2d2d38",borderRadius:12,padding:16,background:"#15151d",margin:"12px 0"}
const button:CSSProperties={minHeight:44,padding:"8px 12px",borderRadius:8,border:"1px solid #4b5563",background:"#111827",color:"#e5e7eb",cursor:"pointer"}
const active:CSSProperties={...button,border:"2px solid #60a5fa",background:"#172554"}

function bounds(points:Array<{x:number;y:number}>){const xs=points.map(p=>p.x),ys=points.map(p=>p.y);return{minX:Math.min(...xs,0),maxX:Math.max(...xs,1),minY:Math.min(...ys,0),maxY:Math.max(...ys,1)}}

export function GeometrySvgView({data,mode,onSubmit,disabled}:{data:GeometryCanvasDataSpec;mode:VisualInteractionMode;onSubmit?:(verb:VisualInteractionVerb,response:unknown)=>void;disabled?:boolean}){
  const [selected,setSelected]=useState("");const byId=new Map(data.points.map(p=>[p.id,p]));const box=bounds(data.points);const pad=35,w=560,h=330
  const sx=(x:number)=>pad+(x-box.minX)/(box.maxX-box.minX||1)*(w-pad*2),sy=(y:number)=>h-pad-(y-box.minY)/(box.maxY-box.minY||1)*(h-pad*2)
  const select=(id:string,verb:VisualInteractionVerb)=>{setSelected(id);if(mode!=="teach")onSubmit?.(verb,id)}
  const info=(()=>{const p=byId.get(selected);if(p)return`${p.label||p.id}: (${p.x}, ${p.y})`;const s=data.segments.find(x=>x.id===selected);if(s){const a=byId.get(s.from),b=byId.get(s.to);const derived=a&&b?Math.hypot(b.x-a.x,b.y-a.y):null;return`${s.label||s.id}${s.measurement!==undefined?`: ${s.measurement} ${s.unit||""}`:derived!==null?`: longitud derivada ${Number(derived.toFixed(3))}`:""}`}const a=data.angles?.find(x=>x.id===selected);return a?`${a.label||a.id}${a.degrees!==undefined?`: ${a.degrees}°`:""}`:"Selecciona un objeto para explorar sus datos grounded."})()
  return <div style={card} data-testid="geometry-canvas" role="group" aria-label="Construcción geométrica interactiva">
    <svg viewBox={`0 0 ${w} ${h}`} style={{width:"100%",height:"auto",display:"block",background:"#0c0c12",borderRadius:8,touchAction:"manipulation"}}>
      <defs><marker id="geometry-arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6 Z" fill="#93c5fd"/></marker></defs>
      {data.axes&&<><line x1={pad} y1={sy(0)} x2={w-pad} y2={sy(0)} stroke="#475569"/><line x1={sx(0)} y1={pad} x2={sx(0)} y2={h-pad} stroke="#475569"/></>}
      {data.polygons?.map(poly=><polygon key={poly.id} points={poly.points.map(id=>byId.get(id)).filter(Boolean).map(p=>`${sx(p!.x)},${sy(p!.y)}`).join(" ")} fill={selected===poly.id?"rgba(96,165,250,.3)":poly.fill||"rgba(96,165,250,.1)"} stroke="#60a5fa" onClick={()=>select(poly.id,"select_region")}><title>{poly.label||poly.kind||poly.id}</title></polygon>)}
      {data.paths?.map(path=><polyline key={path.id} points={path.points.map(p=>`${sx(p.x)},${sy(p.y)}`).join(" ")} fill="none" stroke={selected===path.id?"#facc15":"#a78bfa"} strokeWidth="3" strokeDasharray={path.kind==="trajectory"?"7 5":undefined} onClick={()=>select(path.id,"select_region")}><title>{path.label||path.kind}</title></polyline>)}
      {data.circles?.map(circle=>{const c=byId.get(circle.center);return c?<circle key={circle.id} cx={sx(c.x)} cy={sy(c.y)} r={Math.abs(sx(c.x+circle.radius)-sx(c.x))} fill="none" stroke={selected===circle.id?"#facc15":"#34d399"} strokeWidth="2" onClick={()=>select(circle.id,"select_region")}><title>{circle.label||circle.id}, radio ${circle.radius}</title></circle>:null})}
      {data.segments.map(segment=>{const a=byId.get(segment.from),b=byId.get(segment.to);if(!a||!b)return null;return <g key={segment.id} tabIndex={0} role="button" aria-label={segment.label||segment.id} onClick={()=>select(segment.id,segment.kind==="vector"?"select_edge":"select_edge")} onKeyDown={e=>{if(e.key==="Enter")select(segment.id,"select_edge")}}><line x1={sx(a.x)} y1={sy(a.y)} x2={sx(b.x)} y2={sy(b.y)} stroke={selected===segment.id?"#facc15":"#93c5fd"} strokeWidth={selected===segment.id?5:3} markerEnd={segment.kind==="vector"||segment.kind==="ray"?"url(#geometry-arrow)":undefined}/><title>{segment.label||segment.id}</title></g>})}
      {data.points.map(point=><g key={point.id} tabIndex={0} role="button" aria-label={`${point.label||point.id} (${point.x}, ${point.y})`} onClick={()=>select(point.id,"select_point")} onKeyDown={e=>{if(e.key==="Enter")select(point.id,"select_point")}}><circle cx={sx(point.x)} cy={sy(point.y)} r={selected===point.id?9:6} fill={selected===point.id?"#facc15":"#60a5fa"}/><text x={sx(point.x)+8} y={sy(point.y)-8} fill="#e5e7eb" fontSize="12">{point.label||point.id}</text></g>)}
    </svg>
    <div aria-live="polite" style={{color:"#93c5fd",fontSize:13,marginTop:8}}>{info}</div>
    {(mode==="practice"||mode==="assess")&&<div style={{marginTop:8,color:"#9ca3af"}}>Selecciona el objeto solicitado directamente en el diagrama.<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:8}}>{data.points.map(point=><button key={point.id} data-geometry-point={point.id} style={selected===point.id?active:button} disabled={disabled} onClick={()=>select(point.id,"select_point")}>{point.label||point.id}</button>)}</div></div>}
  </div>
}

function graphPositions(data:StructureGraphDataSpec){const n=data.nodes.length,w=560,h=320;const indegree=new Map(data.nodes.map(n=>[n.id,0]));data.edges.forEach(e=>indegree.set(e.to,(indegree.get(e.to)||0)+1));if(data.layout==="radial"||data.layout==="network"||data.layout==="molecular")return new Map(data.nodes.map((node,i)=>{const a=-Math.PI/2+i*2*Math.PI/Math.max(n,1);return[node.id,{x:w/2+Math.cos(a)*Math.min(120,25*n),y:h/2+Math.sin(a)*Math.min(120,25*n)}]}));const levels=new Map<string,number>();const visit=(id:string,seen=new Set<string>()):number=>{if(seen.has(id))return 0;const incoming=data.edges.filter(e=>e.to===id);const level=incoming.length?1+Math.max(...incoming.map(e=>visit(e.from,new Set([...seen,id])))):0;levels.set(id,level);return level};data.nodes.forEach(n=>visit(n.id));const groups=new Map<number,string[]>();data.nodes.forEach(n=>{const l=levels.get(n.id)||0;groups.set(l,[...(groups.get(l)||[]),n.id])});const max=Math.max(...groups.keys(),0);const positions=new Map<string,{x:number;y:number}>();for(const [level,ids]of groups)ids.forEach((id,i)=>positions.set(id,{x:50+(i+1)*(460/(ids.length+1)),y:45+level*(230/Math.max(max,1))}));return positions}

export function StructureGraphSvgView({data,mode,onSubmit,disabled}:{data:StructureGraphDataSpec;mode:VisualInteractionMode;onSubmit?:(verb:VisualInteractionVerb,response:unknown)=>void;disabled?:boolean}){
 const [selected,setSelected]=useState("");const pos=useMemo(()=>graphPositions(data),[data]);const pick=(id:string,verb:VisualInteractionVerb)=>{setSelected(id);if(mode!=="teach")onSubmit?.(verb,id)}
 return <div style={card} data-testid="structure-graph"><div style={{color:"#9ca3af",fontSize:13}}>Estructura · layout {data.layout}</div><svg viewBox="0 0 560 320" style={{width:"100%",height:"auto",background:"#0c0c12",borderRadius:8}} role="img" aria-label="Grafo de estructura y relaciones"><defs><marker id="edge-arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0 0 L7 3 L0 6 Z" fill="#64748b"/></marker></defs>{data.edges.map(edge=>{const a=pos.get(edge.from),b=pos.get(edge.to);return a&&b?<g key={edge.id} onClick={()=>pick(edge.id,"select_edge")}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={selected===edge.id?"#facc15":"#64748b"} strokeWidth={selected===edge.id?5:2} markerEnd={edge.directed?"url(#edge-arrow)":undefined}/><title>{edge.label||`${edge.from} → ${edge.to}`}</title></g>:null})}{data.nodes.map(node=>{const p=pos.get(node.id)!;return<g key={node.id} tabIndex={0} role="button" onClick={()=>pick(node.id,"select_node")} onKeyDown={e=>{if(e.key==="Enter")pick(node.id,"select_node")}}><rect x={p.x-58} y={p.y-22} width="116" height="44" rx="12" fill={selected===node.id?"#1d4ed8":"#1f2937"} stroke="#60a5fa"/><text x={p.x} y={p.y+4} fill="#fff" textAnchor="middle" fontSize="12">{node.label.slice(0,18)}</text><title>{node.label}</title></g>})}</svg><div aria-live="polite" style={{color:"#93c5fd",marginTop:8}}>{selected?(data.nodes.find(n=>n.id===selected)?.label||data.edges.find(e=>e.id===selected)?.label||selected):"Selecciona un nodo o relación."}</div></div>
}

export function FlowSvgView({data,mode,onSubmit,disabled}:{data:FlowStateDataSpec;mode:VisualInteractionMode;onSubmit?:(verb:VisualInteractionVerb,response:unknown)=>void;disabled?:boolean}){const [index,setIndex]=useState(0);const [order,setOrder]=useState(data.stages.map(s=>s.id));const activeId=mode==="teach"?data.stages[index]?.id:"";return <div style={card} data-testid="flow-state"><svg viewBox={`0 0 560 ${Math.max(120,data.stages.length*70)}`} style={{width:"100%",height:"auto",background:"#0c0c12",borderRadius:8}}><defs><marker id="flow-arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0 0 L7 3 L0 6 Z" fill="#64748b"/></marker></defs>{data.stages.map((stage,i)=>{const y=45+i*70;return <g key={stage.id} onClick={()=>{setIndex(i);if(mode!=="teach")onSubmit?.("select_stage",stage.id)}}><rect x="160" y={y-22} width="240" height="44" rx="12" fill={activeId===stage.id?"#1d4ed8":"#1f2937"} stroke="#60a5fa"/><text x="280" y={y+4} textAnchor="middle" fill="#fff">{stage.label.slice(0,34)}</text>{i<data.stages.length-1&&<line x1="280" y1={y+22} x2="280" y2={y+48} stroke="#64748b" markerEnd="url(#flow-arrow)"/>}</g>})}</svg>{mode==="teach"?<div style={{display:"flex",gap:8,marginTop:8}}><button style={button} disabled={index===0} onClick={()=>setIndex(i=>i-1)}>Anterior</button><button style={button} disabled={index===data.stages.length-1} onClick={()=>setIndex(i=>i+1)}>Siguiente etapa</button></div>:<button style={button} disabled={disabled} onClick={()=>onSubmit?.("order_sequence",order)}>Comprobar orden</button>}</div>}

export function EquationView({data,mode,onSubmit,disabled}:{data:EquationExpressionDataSpec;mode:VisualInteractionMode;onSubmit?:(verb:VisualInteractionVerb,response:unknown)=>void;disabled?:boolean}){const [step,setStep]=useState(0);return <div style={card} data-testid="equation-expression"><div style={{fontFamily:"serif",fontSize:22,color:"#f8fafc",textAlign:"center",padding:16}}>{data.steps[step]?.expression||data.original}</div><div style={{display:"flex",gap:8,justifyContent:"center"}}>{data.steps.map((item,i)=><button key={item.id} style={step===i?active:button} disabled={disabled} onClick={()=>{setStep(i);if(mode!=="teach")onSubmit?.("transform_expression",item.id)}}>{i+1}</button>)}</div></div>}

export function SourceImageView({data,mode,onSubmit,disabled}:{data:SourceImageDataSpec;mode:VisualInteractionMode;onSubmit?:(verb:VisualInteractionVerb,response:unknown)=>void;disabled?:boolean}){const [zoom,setZoom]=useState(1),[annotations,setAnnotations]=useState(true),[selected,setSelected]=useState(""),[failed,setFailed]=useState(false);const choose=(id:string)=>{setSelected(id);if(mode!=="teach")onSubmit?.("select_hotspot",id)};return <div style={card} data-testid="source-image"><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:8}}><button style={button} onClick={()=>setZoom(z=>Math.min(3,z+.5))}>Ampliar</button><button style={button} onClick={()=>setZoom(z=>Math.max(1,z-.5))}>Reducir</button><button style={button} onClick={()=>setZoom(1)}>Restablecer</button><button style={button} aria-pressed={annotations} onClick={()=>setAnnotations(v=>!v)}>Anotaciones</button></div>{failed?<div role="note" style={{padding:20,color:"#cbd5e1"}}>La figura no está disponible. {data.alt}</div>:<div style={{overflow:"auto",maxHeight:520,borderRadius:8,touchAction:"pan-x pan-y"}}><div style={{position:"relative",width:`${zoom*100}%`,minWidth:"100%"}}><img src={data.src} alt={data.alt} style={{display:"block",width:"100%",height:"auto"}} onError={()=>setFailed(true)}/>{annotations&&data.hotspots.map(h=><button key={h.id} aria-label={h.label} disabled={disabled} onClick={()=>choose(h.id)} style={{position:"absolute",left:`${h.x*100}%`,top:`${h.y*100}%`,width:Math.max(32,(h.radius||.04)*200),height:Math.max(32,(h.radius||.04)*200),transform:"translate(-50%,-50%)",borderRadius:"50%",border:selected===h.id?"3px solid #facc15":"2px solid #60a5fa",background:"rgba(59,130,246,.18)"}}><span style={{position:"absolute",left:"100%",top:0,color:"white",background:"#111827",padding:"2px 5px",whiteSpace:"nowrap"}}>{h.label}</span></button>)}</div></div>}<div style={{color:"#9ca3af",marginTop:8}}>Página {data.page||"—"} · {data.alt}</div></div>}
