import assert from 'node:assert/strict'
import { NextRequest } from 'next/server'
import { buildSourceSelectionSnapshot } from '../../lib/adaptive/sourceSelection'
import { POST, __routeDeps } from '../../app/api/alai-studyal-repasar/route'

// ============================================================
// LIVE RETEST #3 — the mocked-helper-only tests (repasar-evidence-
// status-invariant-contracts.ts) proved reconcileCoverageEvidenceInvariant
// works in isolation, but live still showed "10 correct / 0 partial / 41
// omitted" with a rendered "Dijiste: <real quote>" on RED targets. This
// file drives the REAL POST handler end to end (raw provider mock ->
// reconcile -> domainMap -> conceptStatus -> HTTP response) to prove the
// full wiring, not just the helper.
//
// Root cause found by code trace (no live provider call needed): the UI's
// "Dijiste" text was sourced from conceptStatus[].said — generated by the
// SEPARATE persona/feedback call — which is completely decoupled from the
// canonical batch call's own `evidence` field. A canonical `missing` verdict
// with a genuinely empty `evidence` (i.e. the invariant correctly left it
// omitted) could still surface a persona-hallucinated "said" quote,
// because reconcileConceptStatus previously trusted the model's own
// "said" wording unconditionally. Fixed by giving `said` ONE canonical
// source: the same evidence string that decided the target's status
// (lib: sourceConceptMap.canonicalEvidence -> reconcileConceptStatus).
//
// Also raised evaluateRepasarCoverageBatch's maxTokens (3000 -> 6000) and
// added `recoverableArrayKeys` — the added `evidence` field roughly
// doubled that call's output size, and a truncated/malformed response
// with no recovery path previously defaulted the ENTIRE batch to
// omitted, not just the targets the model actually judged missing.
// ============================================================

const selection = buildSourceSelectionSnapshot(['mat-a'], { 'mat-a': [1] })
const STUDENT_SENTENCE = 'El equilibrio químico ocurre cuando la reacción directa y la inversa pasan a la misma velocidad.'

const payload = {
  sourceSelectionFingerprint: selection.fingerprint,
  topicsIndex: [{ id: 'topic-1', title: 'Equilibrio', order: 0 }],
  globalOrderedAnalysis: [
    {
      id: 't-def', kind: 'concept', name: 'Definición de Equilibrio Químico',
      summary: 'El equilibrio químico es un estado dinámico de velocidades iguales.',
      importance: 90, materialId: 'mat-a', pages: [1], sourceSpans: [{ page: 1, quote: STUDENT_SENTENCE }],
      topicId: 'topic-1', globalOrder: 0,
    },
    {
      id: 't-condicion', kind: 'concept', name: 'Condición de equilibrio químico',
      summary: 'La condición de equilibrio se cumple cuando la velocidad directa iguala a la inversa.',
      importance: 60, materialId: 'mat-a', pages: [1], sourceSpans: [{ page: 1, quote: 'la velocidad directa iguala a la inversa' }],
      topicId: 'topic-1', globalOrder: 1,
    },
    {
      id: 't-igualdad', kind: 'concept', name: 'Igualdad de velocidades en el equilibrio',
      summary: 'La igualdad se expresa formalmente como kf [N2O4] = kr [NO2]^2.',
      importance: 60, materialId: 'mat-a', pages: [1], sourceSpans: [{ page: 1, quote: 'kf [N2O4] = kr [NO2]^2' }],
      topicId: 'topic-1', globalOrder: 2,
    },
    {
      id: 't-kp', kind: 'concept', name: 'Constante Kp y presiones parciales',
      summary: 'Kp relaciona el equilibrio con presiones parciales.',
      importance: 40, materialId: 'mat-a', pages: [1], sourceSpans: [{ page: 1, quote: 'Kp relaciona el equilibrio con presiones parciales.' }],
      topicId: 'topic-1', globalOrder: 3,
    },
  ],
  uniqueConceptsIndex: [],
}

function installMocks(canonicalCoverage: { targetId: string; status: string; evidence?: string }[]) {
  const snapshots = new Map<string, any>()
  Object.assign(__routeDeps, {
    getServerSession: async () => ({ user: { id: 'user-1' } }),
    getAuthoritativeFreeSession: async () => ({ id: 'sess-live', userId: 'user-1', processMode: 'free', sourceSelection: selection }),
    getMaterial: async () => ({ id: 'mat-a' }),
    lookupEnjoyer: async (fingerprint: string) => (fingerprint === selection.fingerprint ? payload : null),
    createRepasarSnapshotStore: () => ({
      async get(id: string) { return snapshots.get(id) || null },
      async set(snapshot: any) { snapshots.set(snapshot.snapshotId, snapshot) },
    }),
    generateValidatedLegacyJson: async ({ telemetryContext, validate }: any) => {
      const value = telemetryContext?.phase === 'analysis_batch'
        ? { targetCoverage: canonicalCoverage }
        : {
          // The persona/feedback call independently hallucinates a "said"
          // quote for the RED targets, exactly reproducing the live bug's
          // shape — this is what proves the fix, not the mock's absence.
          score: 30, feedback: 'Buen inicio.', summary: 'Cobertura parcial.',
          conceptStatus: [
            { concept: 'Definición de Equilibrio Químico', status: 'mastered', importance: 'critical', said: STUDENT_SENTENCE, missing: '' },
            { concept: 'Condición de equilibrio químico', status: 'weak', importance: 'supporting', said: STUDENT_SENTENCE, missing: 'Formalizar la condición.' },
            { concept: 'Igualdad de velocidades en el equilibrio', status: 'weak', importance: 'supporting', said: STUDENT_SENTENCE, missing: 'kf [N2O4] = kr [NO2]^2' },
            { concept: 'Constante Kp y presiones parciales', status: 'weak', importance: 'supporting', said: 'no dijo nada de Kp pero igual lo invento', missing: 'Kp' },
          ],
          strengths: [], missingConcepts: [], confusions: [],
          repair: { question: '', topicLabel: '', targetConcepts: [], requiredFacts: [], optionalFacts: [], targetIds: [] },
        }
      assert.equal(validate(value).valid, true)
      return value
    },
  })
  return snapshots
}

function extractRequestedTargetIds(messages: any[]): string[] {
  const text = (messages || []).map((m: any) => String(m?.content || '')).join('\n')
  return [...text.matchAll(/\[TARGET (\S+?)\]/g)].map(match => match[1])
}

/** Like installMocks, but the canonical coverage response is computed
 *  dynamically per call from the actual requested target ids — needed to
 *  test the retry-round loop, where later rounds request a strictly
 *  smaller id set than the first. */
function installMocksDynamicCoverage(coverageFn: (requestedIds: string[], callIndex: number) => any[]) {
  const snapshots = new Map<string, any>()
  let analysisBatchCallIndex = 0
  Object.assign(__routeDeps, {
    getServerSession: async () => ({ user: { id: 'user-1' } }),
    getAuthoritativeFreeSession: async () => ({ id: 'sess-live', userId: 'user-1', processMode: 'free', sourceSelection: selection }),
    getMaterial: async () => ({ id: 'mat-a' }),
    lookupEnjoyer: async (fingerprint: string) => (fingerprint === selection.fingerprint ? payload : null),
    createRepasarSnapshotStore: () => ({
      async get(id: string) { return snapshots.get(id) || null },
      async set(snapshot: any) { snapshots.set(snapshot.snapshotId, snapshot) },
    }),
    generateValidatedLegacyJson: async ({ telemetryContext, validate, messages }: any) => {
      if (telemetryContext?.phase === 'analysis_batch') {
        const requestedIds = extractRequestedTargetIds(messages)
        const value = { targetCoverage: coverageFn(requestedIds, analysisBatchCallIndex++) }
        assert.equal(validate(value).valid, true)
        return value
      }
      const value = {
        score: 30, feedback: 'ok', summary: 'ok', conceptStatus: [], strengths: [], missingConcepts: [], confusions: [],
        repair: { question: '', topicLabel: '', targetConcepts: [], requiredFacts: [], optionalFacts: [], targetIds: [] },
      }
      assert.equal(validate(value).valid, true)
      return value
    },
  })
  return { getAnalysisBatchCallCount: () => analysisBatchCallIndex }
}

async function callEvaluate() {
  return POST(new NextRequest('http://localhost/api/alai-studyal-repasar', {
    method: 'POST', headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ sessionId: 'sess-live', explanation: STUDENT_SENTENCE, mode: 'nino' }),
  }))
}

async function testEvidenceBackedMissingBecomesPartialEndToEnd() {
  // A. raw `missing` + meaningful evidence becomes partial, end to end.
  installMocks([
    { targetId: 't-def', status: 'covered', evidence: STUDENT_SENTENCE, demonstrated: STUDENT_SENTENCE },
    { targetId: 't-condicion', status: 'missing', evidence: STUDENT_SENTENCE, demonstrated: STUDENT_SENTENCE, missingDetail: 'falta formalizar la condición de igualdad' },
    { targetId: 't-igualdad', status: 'missing', evidence: STUDENT_SENTENCE, demonstrated: STUDENT_SENTENCE, missingDetail: 'falta la fórmula kf [N2O4] = kr [NO2]^2' },
    { targetId: 't-kp', status: 'missing', evidence: '' },
  ])
  const response = await callEvaluate()
  const data = await response.json()
  assert.equal(response.status, 200)

  // C. domain map (aggregate, server-authoritative) counts it as demonstrated_partial.
  const gapById = new Map(data.analysis.domainMap.gaps.map((g: any) => [g.id, g.status]))
  assert.equal(gapById.get('t-condicion'), 'demonstrated_partial', 'A/C: evidence-backed missing becomes demonstrated_partial')
  assert.equal(gapById.get('t-igualdad'), 'demonstrated_partial')
  // D. "no aparecieron" (omitted) count excludes it.
  assert.equal(data.analysis.domainMap.omitted, 1, 'D: only the genuinely absent Kp target remains omitted')
  assert.equal(data.analysis.domainMap.demonstratedPartial, 2)
  assert.equal(data.analysis.domainMap.demonstratedCorrect, 1)

  // E. rendered bucket is "Conviene profundizar" (progress), not "weak".
  const condicion = data.analysis.conceptStatus.find((c: any) => c.concept === 'Condición de equilibrio químico')
  const igualdad = data.analysis.conceptStatus.find((c: any) => c.concept === 'Igualdad de velocidades en el equilibrio')
  assert.equal(condicion.status, 'progress', 'E: rendered bucket is progress ("Conviene profundizar"), never weak/red')
  assert.equal(igualdad.status, 'progress')

  // F. targetId remains identical throughout (implicit — same ids used to look up above).

  // G. truly absent Kp remains omitted, in both domainMap and rendered bucket.
  const kp = data.analysis.conceptStatus.find((c: any) => c.concept === 'Constante Kp y presiones parciales')
  assert.equal(gapById.get('t-kp'), 'omitted', 'G: Kp stays omitted')
  assert.equal(kp.status, 'weak', 'G: Kp renders in the weak/red bucket, unlike the evidence-backed targets')

  console.log('repasar-full-pipeline-evidence: A/C/D/E/F/G PASS')
}

async function testUiDijisteCannotDivergeFromCanonicalStatus() {
  // B. no later transform can revert it to omitted, AND the persona
  // call's own hallucinated "said" text can never surface for a target
  // whose canonical evidence disagrees with it (the exact live bug).
  installMocks([
    { targetId: 't-def', status: 'covered', evidence: STUDENT_SENTENCE, demonstrated: STUDENT_SENTENCE },
    { targetId: 't-condicion', status: 'missing', evidence: STUDENT_SENTENCE, demonstrated: STUDENT_SENTENCE, missingDetail: 'falta formalizar la condición de igualdad' },
    { targetId: 't-igualdad', status: 'missing', evidence: STUDENT_SENTENCE, demonstrated: STUDENT_SENTENCE, missingDetail: 'falta la fórmula kf [N2O4] = kr [NO2]^2' },
    { targetId: 't-kp', status: 'missing', evidence: '' },
  ])
  const response = await callEvaluate()
  const data = await response.json()

  const condicion = data.analysis.conceptStatus.find((c: any) => c.concept === 'Condición de equilibrio químico')
  const igualdad = data.analysis.conceptStatus.find((c: any) => c.concept === 'Igualdad de velocidades en el equilibrio')
  const kp = data.analysis.conceptStatus.find((c: any) => c.concept === 'Constante Kp y presiones parciales')

  // B: still partial/correct after the full response is built — nothing downstream reverted it.
  assert.equal(condicion.status, 'progress')
  assert.equal(igualdad.status, 'progress')

  // "Dijiste" (said) is sourced from the canonical evidence, matching
  // exactly what backed the status — not the persona call's own wording.
  assert.equal(condicion.said, STUDENT_SENTENCE, '"Dijiste" matches the canonical evidence used to decide the status')
  assert.equal(igualdad.said, STUDENT_SENTENCE)

  // The live bug specifically: Kp's canonical evidence is empty (genuinely
  // never mentioned), so even though the persona call hallucinated a
  // "said" quote for it, the rendered "Dijiste" must be empty — a
  // canonically-omitted target can never display fabricated evidence text.
  assert.equal(kp.said, '', 'a canonically-omitted target never surfaces a hallucinated "Dijiste" quote')

  console.log('repasar-full-pipeline-evidence: B + UI-DIJISTE-SINGLE-SOURCE PASS')
}

async function testTruncatedCanonicalBatchIsRetriedNotBlanketOmitted() {
  // Adaptive-complete-coverage fix: a canonical batch response that only
  // partially answers (as a truncation event would look) must NOT
  // silently default the unanswered targets to "omitted" — those are
  // TRANSPORT-unadjudicated, not academic missing. The route must retry
  // them in a bounded follow-up round; here the retry round succeeds,
  // so the attempt eventually completes 4/4 with the correct statuses.
  // Coverage table keyed by id — deliberately independent of exact batch/
  // split geometry (the resolver may retry the 2 still-unresolved ids
  // together OR split them into separate single-id batches; either is a
  // valid bounded-recovery strategy). Round 1 only ever answers for
  // t-def/t-condicion; whichever later call(s) request t-igualdad/t-kp
  // get their real verdict, proving retry recovers them without ever
  // re-requesting the already-settled pair.
  const settledIds = new Set<string>()
  const table: Record<string, any> = {
    't-def': { targetId: 't-def', status: 'covered', evidence: STUDENT_SENTENCE, demonstrated: STUDENT_SENTENCE },
    't-condicion': { targetId: 't-condicion', status: 'partial', evidence: STUDENT_SENTENCE, demonstrated: STUDENT_SENTENCE, missingDetail: 'falta formalizar la condición de igualdad' },
    't-igualdad': { targetId: 't-igualdad', status: 'partial', evidence: STUDENT_SENTENCE, demonstrated: STUDENT_SENTENCE, missingDetail: 'falta la fórmula kf [N2O4] = kr [NO2]^2' },
    't-kp': { targetId: 't-kp', status: 'missing', evidence: '' },
  }
  installMocksDynamicCoverage((requestedIds, callIndex) => {
    for (const id of requestedIds) {
      assert.ok(!settledIds.has(id), `retry re-requested an already-settled id: ${id}`)
    }
    if (callIndex === 0) {
      // First (only) round-1 batch: only answers for 2 of the 4 requested ids.
      settledIds.add('t-def'); settledIds.add('t-condicion')
      return [table['t-def'], table['t-condicion']]
    }
    return requestedIds.map(id => table[id]).filter(Boolean)
  })
  const response = await callEvaluate()
  const data = await response.json()
  assert.equal(response.status, 200, 'the attempt completes once the retry round fills in the remaining targets')
  const gapById = new Map(data.analysis.domainMap.gaps.map((g: any) => [g.id, g.status]))
  const strengthIds = new Set(data.analysis.domainMap.strengths.map((s: any) => s.id))
  assert.ok(strengthIds.has('t-def'), 'entries that DID arrive in round 1 are never discarded by the retry')
  assert.equal(gapById.get('t-condicion'), 'demonstrated_partial')
  assert.equal(gapById.get('t-igualdad'), 'demonstrated_partial', 'a target recovered in the retry round is adjudicated normally, never fabricated as omitted')
  assert.equal(data.analysis.domainMap.omitted, 1, 'only the genuinely-adjudicated-missing Kp counts as omitted')
  assert.equal(data.analysis.domainMap.totalAcademicTargets, 4)
  console.log('repasar-full-pipeline-evidence: RETRY-RECOVERS-PARTIAL-BATCH PASS')
}

async function testRetryExhaustionReturnsExplicitIncompleteError() {
  // The provider NEVER answers for t-igualdad/t-kp, across every round.
  // After REPASAR_MAX_ADJUDICATION_ROUNDS the route must return an
  // explicit retryable failure — never persist/return a domainMap that
  // quietly renders the two stuck targets as "no aparecieron".
  installMocksDynamicCoverage(() => [
    { targetId: 't-def', status: 'covered', evidence: STUDENT_SENTENCE, demonstrated: STUDENT_SENTENCE },
    { targetId: 't-condicion', status: 'partial', evidence: STUDENT_SENTENCE, demonstrated: STUDENT_SENTENCE, missingDetail: 'x' },
  ])
  const response = await callEvaluate()
  const data = await response.json()
  assert.equal(response.status, 409)
  assert.equal(data.error, 'REPASAR_COVERAGE_INCOMPLETE_RETRYABLE')
  assert.equal(data.totalTargets, 4)
  assert.equal(data.adjudicatedCount, 2)
  assert.deepEqual([...data.remainingTargetIds].sort(), ['t-igualdad', 't-kp'])
  console.log('repasar-full-pipeline-evidence: RETRY-EXHAUSTION-EXPLICIT-ERROR PASS')
}

async function main() {
  await testEvidenceBackedMissingBecomesPartialEndToEnd()
  await testUiDijisteCannotDivergeFromCanonicalStatus()
  await testTruncatedCanonicalBatchIsRetriedNotBlanketOmitted()
  await testRetryExhaustionReturnsExplicitIncompleteError()
  console.log('repasar-full-pipeline-evidence-contracts: ALL PASS')
}

main().catch(error => { console.error(error); process.exit(1) })
